server:
  port: 8050
spring:
  application:
    name: microservice-config-server-eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/


---
spring:
  profiles:
    active: native #开发环境读取本地文件
  cloud:
    config:
      server:
        native:
          search-locations: /Users/chenshunyang/code/study/spring-cloud-microservice-study/config-repo

---
spring:
  profiles:
    active: online #线上环境读取git仓库
  cloud:
    config:
      server:
        git:
          uri: https://github.com/eacdy/spring-cloud-study/     # 配置git仓库的地址
          search-paths: config-repo                             # git仓库地址下的相对地址，可以配置多个，用,分割。
          username:                                             # git仓库的账号
          password: